### PR TITLE
Add go1.11

### PR DESCRIPTION
**Pull request by pierre-emmanuelJ**
Add go1.11 to travis

### CODE REVIEW

**Comment by pierre-emmanuelJ** [comment]
👍 agree with you

**Comment by pierre-emmanuelJ** [comment]
as you say in #298 I think we have to split
image

**Comment by greut** [comment]
M'kay @pierre-emmanuelJ, let's consult the oracles.

@pyr, @ste-m the best thing w.r.t go1.11 is to move the cli to its own home back again. Meaning egoscale will only contain the library side of the story and `exoscale/cli` (TBD) will be shiny cli. Much like `minio-go` and `mc`.

**Comment by greut** [comment]
or #164 which wouldn't have any `go.mod` at the root directory.

**Comment by ste-m** [comment]
I need 5 minutes of @pyr to discuss two things face to face prior merging this one :)

**Comment by greut** [comment]
no worries, no merging :)

**Comment by pierre-emmanuelJ** [comment]
👍

**Comment by greut** [comment]
I'll redo this once exo is properly moved to exoscale/cli

**Pull request closed without merging**
