### PR TITLE
updateNetwork: add missing startip, endip, netmask

### PR DESCRIPTION
**Pull request by greut**
https://community.exoscale.com/api/compute/#updatenetwork_GET

### CODE REVIEW

**Comment by mcorbin** [comment]
Don't forget #327 :p

**Comment by greut** [comment]
@mcorbin what do you mean?

**Comment by mcorbin** [comment]
I also updated the updateNetwork call in my PR.

**Comment by greut** [comment]
@mcorbin do you mind if this go through while you take time to polish the `exo` command?

**Comment by mcorbin** [comment]
@greut No problem ;)

**Comment by greut** [comment]
It will conflicts with #332 but it's generated code. Sorry @mcorbin for the forced rebase.

**Pull request merged**
