### PR TITLE
Add support for external-sources

### PR DESCRIPTION
**Pull request by pyr**

### CODE REVIEW

**Review by exo-cedric — APPROVED** [review]
LGTM

(can't we get rid of the `oapi.NewPoller()` duplication ?)

**Comment by falzm** [comment]
> LGTM
> 
> (can't we get rid of the `oapi.NewPoller()` duplication ?)

What duplication? Those are 2 different execution scopes (2 different methods).

**Comment by pyr** [comment]
> What duplication? Those are 2 different execution scopes (2 different methods).

You mean reducing this to something more succinct since it's code that lives in many of these methods?

```go
	_, err = oapi.NewPoller().
		WithTimeout(c.timeout).
		WithInterval(c.pollInterval).
		Poll(ctx, c.OperationPoller(zone, *resp.JSON200.Id))
	if err != nil {
		return err
	}
```

If so, I don't think it would belong in this PR since it is the way the whole code base is structured, deviating here would introduce an exception for these two calls.

**Review by PhilippeChepy — APPROVED** [review]

**Review by falzm — APPROVED** [review]
Cosmetic edits, otherwise LGTM 👍

**Comment by pyr** [comment]
Thanks @falzm  for helping with the tests!

**Pull request merged**
