### PR TITLE
request: add context to http calls

### PR DESCRIPTION
**Pull request by greut**
- `timeout` parameter to the client, set by default to `60` (like `go-cloudstack`)
- `retryStrategy` parameter to the client, set by default to a Fibonacci sequence (because nerd)
- addition `RequestWithContext(ctx, command) (interface{}, error)`
- addition `AsyncRequestWithContext(ctx, command) (interface{}, error)`
- addition `BooleanRequestWithContext(ctx, command) error`
- addition `BooleanAsyncRequestWithContext(ctx, command) error`
- changes `AsyncRequest(command) (interface, error)` (no more `AsyncInfo`)

See #42

### CODE REVIEW

**Comment by vincentbernat** [comment]
More changes than just adding context?

**Comment by greut** [comment]
@vincentbernat I'm thinking about removing the `AsyncInfo` thingy. You either set a default timeout in the client if you don't care about it, or use a `Context` and manage it yourself.

**Comment by vincentbernat** [comment]
I think that's a good idea (to rely on known mechanism).

**Comment by greut** [comment]
@vincentbernat there is only `Command` now, and a ton of juggling with goroutines.

- `Request(Command) (interface{}, error)`
- `RequestWithContext(context.Context, Command) (interface{}, error)`
- `BooleanRequest(Command) error`
- `BooleanRequestWithContext(context.Context, Command) error`

I'll have to try it on TF to convince myself though...

**Comment by greut** [comment]
:warning: breaks https://github.com/xenolf/lego/ :warning:

**Pull request merged**
