### PR TITLE
Website using Hugo

### PR DESCRIPTION
**Pull request by greut**
- [x] make it work
- [x] make it nice
- [x] make it public )

(cf. #144 #143)

### CODE REVIEW

**Comment by greut** [comment]
screenshot from 2018-06-08 12-46-49

**Comment by pierre-emmanuelJ** [comment]
👍

**Comment by greut** [comment]
screenshot from 2018-06-08 13-39-01
screenshot from 2018-06-08 13-36-38

**Comment by greut** [comment]
it sort of does all the things from the todo ;-)

**Pull request merged**
