### PR TITLE
privnet: updateNetwork call

### PR DESCRIPTION
**Pull request by mcorbin**
This call can be used to update an existing private network.

### CODE REVIEW

**Comment by greut** [comment]
please show us a usage example.

**Comment by mcorbin** [comment]
```
exo privnet create --name foo
┼──────┼─────────────┼──────────────────────────────────────┼──────┼
│ NAME │ DESCRIPTION │                  ID                  │ DHCP │
┼──────┼─────────────┼──────────────────────────────────────┼──────┼
│ foo  │             │ e84d6a71-4d15-4c74-9080-90519f2182d7 │ n/a  │
┼──────┼─────────────┼──────────────────────────────────────┼──────┼

exo privnet update --id e84d6a71-4d15-4c74-9080-90519f2182d7 --startip 10.0.0.20 --endip 10.0.0.50 --netmask 255.255.255.0
Updating the network "e84d6a71-4d15-4c74-9080-90519f2182d7" . success.
┼──────┼─────────────┼──────────────────────────────────────┼─────────────────────────┼
│ NAME │ DESCRIPTION │                  ID                  │          DHCP           │
┼──────┼─────────────┼──────────────────────────────────────┼─────────────────────────┼
│ foo  │             │ e84d6a71-4d15-4c74-9080-90519f2182d7 │ 10.0.0.20-10.0.0.50 /24 │
┼──────┼─────────────┼──────────────────────────────────────┼─────────────────────────┼
```

**Comment by vincentbernat** [comment]
I don't know if `exo` already has netmasks somewhere, but I would welcome the use of `--mask 24` instead of `--netmask 255.255.255.0`. The dotted quad notations for mask is always painful to deal with, I think most people prefer to handle a mask length rather than an obscure netmask.

**Comment by mcorbin** [comment]
I rebased against master. Example: `exo privnet update da9b7b1b-8906-4e0d-9f42-09a985044f02 --startip 11.0.0.1 --endip 11.0.0.200 --netmask 255.255.255.0`

**Comment by greut** [comment]
By id or by name is always great when it comes to human.

```console
% exo privnet create foo

% exo privnet update foo --startip 10.0.0.1 --endip 10.0.0.2 --netmask 255.255.255.0
update the network by ID, got "foo"
```

**Comment by mcorbin** [comment]
But the name is not unique in Cloudstack, I can have multiple networks with the same name.

**Comment by mcorbin** [comment]
But the name is not unique in Cloudstack, I can have multiple networks with the same name.

**Comment by greut** [comment]
indeed.

**Comment by mcorbin** [comment]
@greut What happens when the user have 2 networks with the same name ?

**Comment by greut** [comment]
@mcorbin basically what happens when you have two instances with same name.

**Comment by mcorbin** [comment]
`exo privnet update <name>` now works.

**Pull request merged**
