### PR TITLE
Add egoscale-cli

### PR DESCRIPTION
**Pull request by pierre-emmanuelJ**
Signed-off-by: Pierre-Emmanuel Jacquier <pierre-emmanuel.jacquier@epitech.eu>

### CODE REVIEW

**Comment by greut** [comment]
you may remove the LICENSE file and udpate .travis.yml accordingly.

**Comment by greut** [comment]
Good job!

**Comment by greut** [comment]
the duplication for golint/go vet/etc. shouldn't be required though

**Comment by pierre-emmanuelJ** [comment]
@greut  ready to be released !

**Pull request merged**
