### PR TITLE
Less types

### PR DESCRIPTION
**Pull request by greut**
An attempt to remove most of the `<Foo>Response` type. We have to keep them for the `List<Foo>s` commands though.

**Old**

https://godoc.org/github.com/exoscale/egoscale#pkg-index

**New**

screenshot-2018-5-7 egoscale - the go programming language

### CODE REVIEW

**Comment by greut** [comment]
more help for the debug mode

```
$ cs -d destroyVirtualMachine --id 1
https://api.exoscale.ch/compute\
?apikey=EXO34771c9dad3d915cf1aa559e\
&command=destroyVirtualMachine\
&id=1\
&response=json

FIELD                 TYPE            DOCUMENTATION
account               string          the account associated with the virtual machine
affinitygroup         []AffinityGroup list of affinity groups associated with the virtual machine
clusterid             string          the ID of the vm's cluster
clustername           string          the name of the vm's cluster
cpunumber             int             the number of cpu this virtual machine is running with
cpuspeed              int             the speed of each cpu
cpuused               string          the amount of the vm's CPU currently used
created               string          the date when this virtual machine was created
details                               Vm details in key/value pairs.
diskioread            int64           the read (io) of disk on the vm
diskiowrite           int64           the write (io) of disk on the vm
diskkbsread           int64           the read (bytes) of disk on the vm
diskkbswrite          int64           the write (bytes) of disk on the vm
diskofferingid        string          the ID of the disk offering of the virtual machine
diskofferingname      string          the name of the disk offering of the virtual machine
displayname           string          user generated name. The name of the virtual machine is returned if no displayname exists.
displayvm             bool            an optional field whether to the display the vm to the end user or not.
domain                string          the name of the domain in which the virtual machine exists
domainid              string          the ID of the domain in which the virtual machine exists
forvirtualnetwork     bool            the virtual network for the service offering
group                 string          the group name of the virtual machine
groupid               string          the group ID of the virtual machine
haenable              bool            true if high-availability is enabled, false otherwise
hostid                string          the ID of the host for the virtual machine
hostname              string          the name of the host for the virtual machine
hypervisor            string          the hypervisor on which the template runs
id                    string          the ID of the virtual machine
instancename          string          instance name of the user vm; this parameter is returned to the ROOT admin only
isdynamicallyscalable bool            true if vm contains XS/VMWare tools inorder to support dynamic scaling of VM cpu/memory.
isodisplaytext        string          an alternate display text of the ISO attached to the virtual machine
isoid                 string          the ID of the ISO attached to the virtual machine
isoname               string          the name of the ISO attached to the virtual machine
keypair               string          ssh key-pair
memory                int             the memory allocated for the virtual machine
name                  string          the name of the virtual machine
networkkbsread        int64           the incoming network traffic on the vm
networkkbswrite       int64           the outgoing network traffic on the host
nic                   []Nic           the list of nics associated with vm
oscategoryid          string          Os category ID of the virtual machine
password              string          the password (if exists) of the virtual machine
passwordenabled       bool            true if the password rest feature is enabled, false otherwise
pcidevices            []string        list of PCI devices
podid                 string          the ID of the vm's pod
podname               string          the name of the vm's pod
project               string          the project name of the vm
projectid             string          the project id of the vm
publicip              string          public IP address id associated with vm via Static nat rule
publicipid            string          public IP address id associated with vm via Static nat rule
rootdeviceid          int64           device ID of the root volume
rootdevicetype        string          device type of the root volume
securitygroup         []SecurityGroup list of security groups associated with the virtual machine
serviceofferingid     string          the ID of the service offering of the virtual machine
serviceofferingname   string          the name of the service offering of the virtual machine
servicestate          string          State of the Service from LB rule
state                 string          the state of the virtual machine
tags                  []ResourceTag   the list of resource tags associated with vm
templatedisplaytext   string           an alternate display text of the template for the virtual machine
templateid            string          the ID of the template for the virtual machine. A -1 is returned if the virtual machine was created from an ISO file.
templatename          string          the name of the template for the virtual machine
zoneid                string          the ID of the availablility zone for the virtual machine
zonename              string          the name of the availability zone for the virtual machine
```

**Comment by pierre-emmanuelJ** [comment]
A best way to return responses i agree with you 👍

**Comment by greut** [comment]
@pierre-emmanuelJ thanks!

**Comment by greut** [comment]
killer feature: use different theme for each region

screenshot from 2018-05-17 10-36-04

**Comment by marcaurele** [comment]
😋

**Pull request merged**
