### PR TITLE
next gen

### PR DESCRIPTION
**Pull request by greut**
will require a new tag, for `godep` and friends.

### CODE REVIEW

**Comment by marcaurele** [comment]
Do you mind doing a rebase to squash together related commits? Easier to read and better for the history.

**Comment by greut** [comment]
@marcaurele big squash done.

**Comment by greut** [comment]
for the codeclimate/travis overlords:
```
No CODECLIMATE_REPO_TOKEN found. A CODECLIMATE_REPO_TOKEN must be specified as an environment variable.
```

**Comment by greut** [comment]
A list of implemented requests is on the wiki: https://github.com/exoscale/egoscale/wiki#partially-and-fully-implemented

@marcaurele do we miss anything? Having too much is not an issue.

**Pull request merged**
