### PR TITLE
Doc template

### PR DESCRIPTION
**Pull request by greut**
I'm really unsure about how `extractTemplate` is supposed to work, do we need it?

### CODE REVIEW

**Comment by greut** [comment]
:tada: takk

**Comment by greut** [comment]
without `extractTemplate`

**Comment by marcaurele** [comment]
I'm rather swedish compared to @jpmenil , so "tack" works better ;) "tak" for @jpmenil

**Comment by greut** [comment]
fucking swedes

**Comment by greut** [comment]
Norwegians hate everyone equally

**Pull request merged**
